### ISSUE TITLE
Нельзя заливать логи

### ISSUE THREAD

**Issue by Wpert** [mmmarsik/mephi_bot#1]
Во-первых, это бесполезный файл
Во-вторых, на будущее -- это возможное нарушение безопасности как сервиса, так и данных клиентов

Но я готов к обсуждению, возможно есть за этим какая-то логика и существует сценарий, когда логи стоит заливать на гит (но на моей памяти такого нигде нет)

**Comment by mmmarsik** [comment]
Логи действительно не имеет смысла заливать на гит.
Данная информация является исключительно приватной для администратора для последующей отладки.
