### ISSUE TITLE
requirements.txt.

### ISSUE THREAD

**Issue by Wpert** [mmmarsik/mephi_bot#2]
У тебя там буквально ничего нет, если я запущу его на своем сервере, то ничего не получится, так как ты не причислил ни единой либы (2 штуки не в счёт)

**Comment by mmmarsik** [comment]
А что помимо aiogram там должно быть ?

**Comment by Wpert** [comment]
﻿aiofiles
aiogram
aiogram-media-group
aiohttp
aioschedule
aiosignal
async-timeout
asyncpg
attrs

**Comment by mmmarsik** [comment]
добавил еще
sphinx>=5.0,<7.0
docutils<0.18
nbsphinx
sphinx_gallery
ipython
sphinx-autodoc-typehints
furo
pandoc
и пофиксил
