### ISSUE TITLE
config.py

### ISSUE THREAD

**Issue by Wpert** [mmmarsik/mephi_bot#3]
Кмк, это лишний файл, код которого по логике должен быть показан откуда берём мы токен, а не импортим откуда-то из стороннего модуля

**Comment by mmmarsik** [comment]
токен берется из переменной окружения и это видно из кода данного файла. Тебе кажется, что стоит скипнуть прослойку в виде данного файла и перенести его код сразу в bot.py  ?

**Comment by Wpert** [comment]
> токен берется из переменной окружения и это видно из кода данного файла

Мне, как человеку, что читает bot.py это не видно

> Тебе кажется, что стоит скипнуть прослойку в виде данного файла и перенести его код сразу в bot.py ?

Я уверен, что это повысит читаемость, так как очень странно создавать целый файл (либо можно оставить, чтобы затруднить чтение)

**Comment by mmmarsik** [comment]
пофикшено
